#!/bin/sh
set -e

rm -f /etc/ld.so.conf.d/assistente-rs.conf
ldconfig

rm -f /etc/xdg/autostart/assistente-rs.desktop


if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /etc/xdg/autostart/assistente-rs.desktop
fi

exit 0
